In [3]:
!pip install pandas


1. Write a Python program to read a CSV file named `students.csv` and display 
the first 5 rows.

In [9]:

#Write a Python program to read a CSV file named `students.csv` and display the first 5 rows
import pandas as pd
df = pd.read_csv('D:/students.csv')
print(df.head(5))

  Student Name  ID Grade
0          Ram  23     A
1         Hari  12     D
2        Shyam  11     B
3         Rani  15     C
4         Maya  17     A


2. Given a CSV file `sales.csv` with columns: `Product, Price, Quantity`, write 
code to calculate the total sales for each product. 

In [12]:
#Given a CSV file `sales.csv` with columns: `Product, Price, Quantity`, write code to calculate the total sales for each product
df = pd.read_csv('D:/sales.csv')
df['Total Sales'] = df['Price'] * df['Quantity']
result = df.groupby('Product')['Total Sales'].sum().reset_index()
print("Total sales for each product:")
print(result)

Total sales for each product:
      Product  Total Sales
0  Headphones         3900
1      Laptop         6460
2       Phone         8570
3      Tablet         3080


3. How do you handle missing values in a CSV file using Pandas? Write code to 
drop rows with missing values.

In [15]:
# Write code to drop rows with missing values.
df_cleaned = df.dropna()
print("DataFrame after dropping rows with missing values:")
print(df_cleaned)



DataFrame after dropping rows with missing values:
      Product  Price  Quantity  Total Sales
0      Laptop    800         5         4000
1      Laptop    820         3         2460
2       Phone    500        10         5000
3       Phone    510         7         3570
4      Tablet    300         6         1800
5      Tablet    320         4         1280
6  Headphones    100        15         1500
7  Headphones    120        20         2400


4. Write a program to read a CSV file `employees.csv` and extract only the 
`Name` and `Salary` columns

In [16]:
df = pd.read_csv("D:/employees.csv")
result = df[["Name", "Salary"]]
print("Name and Salary columns:")
print(result)


Name and Salary columns:
      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   55000
3    Diana   58000
4    Ethan   62000


5. Write code to save a Pandas DataFrame into a CSV file named `output.csv` 
without the index column. 

In [ ]:
data = {
    "Name": ["Laxman", "Susan", "Pratik"],
    "Salary": [50000, 60000, 55000]
}
df = pd.DataFrame(data)

df.to_csv("output.csv", index=False)

print("DataFrame saved to output.csv without index.")


DataFrame saved to output.csv without index.


6. Write a NumPy program to create a 1D array of numbers from 10 to 50.

In [23]:
#numpy program to create a 1d array of numbers from 10 to 50
import numpy as np
array_1d = np.arange(10, 51)
print("1D array from 10 to 50:")
print(array_1d)

1D array from 10 to 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


7.Write a program to create a 3x3 NumPy array filled with random integers between 1 and 100.

In [24]:
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print("3x3 array with random integers between 1 and 100:")
print(array_3x3)


3x3 array with random integers between 1 and 100:
[[59 84 29]
 [47 27 43]
 [18 60 15]]


8.Write code to reshape a NumPy array of size 12 into a 3x4 matrix.


In [25]:
array_12 = np.arange(12)
matrix_3x4 = array_12.reshape(3, 4)
print("3x4 matrix reshaped from 1D array of size 12:")
print(matrix_3x4)

3x4 matrix reshaped from 1D array of size 12:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


9. How do you compute the mean, median, and standard deviation of 
elements in a NumPy array? Show with an example

In [26]:
array_example = np.array([10, 20, 30, 40, 50])
mean = np.mean(array_example)
median = np.median(array_example)
std_dev = np.std(array_example)
print(f"Mean: {mean}, Median: {median}, Standard Deviation: {std_dev}")


Mean: 30.0, Median: 30.0, Standard Deviation: 14.142135623730951


10. Given two NumPy arrays: 
   
   a = np.array([1, 2, 3]) 
   
   b = np.array([4, 5, 6]) 
   
   Write code to perform element-wise addition, subtraction, and dot product. 

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition = a + b
subtraction = a - b
dot_product = np.dot(a, b)
print(f"Element-wise addition: {addition}")
print(f"Element-wise subtraction: {subtraction}")
print(f"Dot product: {dot_product}")


Element-wise addition: [5 7 9]
Element-wise subtraction: [-3 -3 -3]
Dot product: 32
